version: "3.9"
services:
  frontend-server:
    image: nginx
    build: ./frontend-server
    ports:
      - "8080:80"
    depends_on:
      - api-gateway

  api-gateway:
    image: nginx
    restart: on-failure
    build: ./gateway
    ports:
      - "8000:80"
    depends_on:
      - accounts-service
      - inventory-service

  accounts-service:
    build: ./accounts-service
    restart: on-failure
    depends_on:
      - db1
    environment:
      - DATABASE_URL=postgresql://postgres:password@db1/accounts_db

  db1:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accounts_db

  inventory-service:
    build: ./inventory-service
    restart: on-failure
    depends_on:
      - db2
      - caching-db

  db2:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db
